(function (cjs, an) {

var p; // shortcut to reference prototypes
var lib={};var ss={};var img={};
lib.webFontTxtInst = {}; 
var loadedTypekitCount = 0;
var loadedGoogleCount = 0;
var gFontsUpdateCacheList = [];
var tFontsUpdateCacheList = [];
lib.ssMetadata = [];



lib.updateListCache = function (cacheList) {		
	for(var i = 0; i < cacheList.length; i++) {		
		if(cacheList[i].cacheCanvas)		
			cacheList[i].updateCache();		
	}		
};		

lib.addElementsToCache = function (textInst, cacheList) {		
	var cur = textInst;		
	while(cur != null && cur != exportRoot) {		
		if(cacheList.indexOf(cur) != -1)		
			break;		
		cur = cur.parent;		
	}		
	if(cur != exportRoot) {		
		var cur2 = textInst;		
		var index = cacheList.indexOf(cur);		
		while(cur2 != null && cur2 != cur) {		
			cacheList.splice(index, 0, cur2);		
			cur2 = cur2.parent;		
			index++;		
		}		
	}		
	else {		
		cur = textInst;		
		while(cur != null && cur != exportRoot) {		
			cacheList.push(cur);		
			cur = cur.parent;		
		}		
	}		
};		

lib.gfontAvailable = function(family, totalGoogleCount) {		
	lib.properties.webfonts[family] = true;		
	var txtInst = lib.webFontTxtInst && lib.webFontTxtInst[family] || [];		
	for(var f = 0; f < txtInst.length; ++f)		
		lib.addElementsToCache(txtInst[f], gFontsUpdateCacheList);		

	loadedGoogleCount++;		
	if(loadedGoogleCount == totalGoogleCount) {		
		lib.updateListCache(gFontsUpdateCacheList);		
	}		
};		

lib.tfontAvailable = function(family, totalTypekitCount) {		
	lib.properties.webfonts[family] = true;		
	var txtInst = lib.webFontTxtInst && lib.webFontTxtInst[family] || [];		
	for(var f = 0; f < txtInst.length; ++f)		
		lib.addElementsToCache(txtInst[f], tFontsUpdateCacheList);		

	loadedTypekitCount++;		
	if(loadedTypekitCount == totalTypekitCount) {		
		lib.updateListCache(tFontsUpdateCacheList);		
	}		
};
// symbols:



(lib.largemobiletable = function() {
	this.initialize(img.largemobiletable);
}).prototype = p = new cjs.Bitmap();
p.nominalBounds = new cjs.Rectangle(0,0,320,100);// helper functions:

function mc_symbol_clone() {
	var clone = this._cloneProps(new this.constructor(this.mode, this.startPosition, this.loop));
	clone.gotoAndStop(this.currentFrame);
	clone.paused = this.paused;
	clone.framerate = this.framerate;
	return clone;
}

function getMCSymbolPrototype(symbol, nominalBounds, frameBounds) {
	var prototype = cjs.extend(symbol, cjs.MovieClip);
	prototype.clone = mc_symbol_clone;
	prototype.nominalBounds = nominalBounds;
	prototype.frameBounds = frameBounds;
	return prototype;
	}


(lib.whitelogouse = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AqoZMQk7iEjyjzQjxjxiFk6QiKlGAAljQAAljCKlGQCFk6DxjzQDzjxE6iFQFFiKFjAAQFkAAFFCKQE7CFDxDxQDyDzCFE6QCKFGAAFjQAAFjiKFGQiFE6jyDxQjxDzk7CEQlFCKlkAAQljAAlFiKgALSMVIgBANQAAAPAKAAIAzAAQAMAAgBAKIAACUQAAAHAGACQADACAKABQAKgBAEgCQAFgCAAgIIgBiTQABgKAMAAIAxAAQALAAAAgSQAAgSgMAAIigAAQgGAAgDAIgADSONIBBBGQAHAHATABQANAAAFgFQAGgFgIgIIhOhWQgJgLAKgHIBAg6QAJgKgMgMQgMgMgNALIhKBEQgFAFgEABQgFADgKAAQgKAAAAgOIAAg2QAAgMgRAAQgMAAgDACQgFACgBAIIAAC1QAAANARAAQAVAAAAgNIAAg7QAAgGADgFQAEgEAFAAQATgBALAKgAhwOXQALAAAFAJIAhAyQAFAIARABQAPAAAEgFQAFgEgFgHIgigzQgEgFAHgHQAPgKAIgIQAOgQAAgYQABgfgVgUQgUgSggAAIhsAAQgJAAAAAIIAAC6QAAAMANAAIAPgBQAKgBAAgHIgBgxQABgEADgDQADgDAEAAgAmQOxQAIAAACAHIANAbQAEAHAPABQAIgBAGgCQAJgDgDgGIhXi7QgFgJgLAAQgMAAgEAKIhaC5QgFAMAWAAQASAAADgHIANgXQAEgLAIAAgArGNkIANBsQAAAFAGADQAFADAEAAQAYAAgBgLIgVi2QgCgIgEgDQgDgCgGAAQgLAAgEAIIg8BPQgHAIgEAAQgEABgGgIIg3hPQgGgIgKAAQgKgBgEAFQgDADgCAJIgVCxQAAAGAGADQAFADAFAAQAUAAACgLIANhpQACgIAEABQAEAAADACIAtA9QAEAHAHAAQAFAAAFgGIAwg/QADgEAEABQAFgBACAHgAGyMaIAACwQAAAOANAAICcAAQAKABAAgSQAAgSgKAAIh6AAQgJAAgBgLIAAgdQAAgLAMAAIBFAAQAKAAAAgRQABgTgLABIhHAAQgJAAgBgKIAAgbQAAgJAJAAIB6AAQAHAAADgGQABgEAAgJQAAgJgBgEQgDgEgGAAIicAAQgNAAAAANgAT4IwQgNAOABASQgBASANANQANANATAAQASAAANgNQANgNAAgSQAAgSgNgOQgNgNgSABQgTgBgNANgAP5JKQAlAMA0AAQBUAAAzgtQAygtAAhJQAAghgMgeQgMgegWgXQgUgVgXgSQgWgRgzgkIgqgdQgbgVgMgSQgJgMAAgXQAAgaARgQQASgPAeAAQAsAAAjAbQAPALAFAGQAHAIAOAVQAKAOAMAAQALABAGgHQAIgFgBgJQABgIgCgEIgUhcQgFgXgTAAQgIAAgKAGQgLAIgIAAIgMgCIgWgEQgjgIgmAAQhGAAgrAlQgrAmAAA+QAAAzAgAmQAUAVARAPIBNA3QBBAsAaAdQAcAfgBAhQABAigaAUQgaAWgpAAQglAAgigSQghgTgWgfIgMgRQgJgLgMAAQgLAAgIAIQgIAIAAALQAAAKACAHIAWBUQAEAQAFAHQAGAGALAAQAJAAALgIQAJgJAJABIASAEgAjRF+QAHAAACALIABADQAYBeBFA1QBHA2BlAAQCCAABMhQQBMhRAAiIQAAiFhMhQQhNhQh+ABQhogBhHA3QhFA1gYBgIAAABQgCALgHAAQgIAAgBgKQgYhhhHg2QhHg3hoABQiBAAhLBQQhLBQAACIQgBCFBMBQQBMBQB+AAQBoAABIg2QBHg2AYhfIAAgBQACgLAGAAIABAAgAFnIeQgGAHAAAKQAAANAJAFQAIAEAUADQBeANBrgBQBFABAxgOQAvgOAlgeQAwglAZg+QAZg9AAhOQAAhFgTg3QgVg5glgmQgngng1gSQg1gShOAAQhrAAheANQgUADgIAEQgJAFAAANQAAAJAGAIQAFAGAJABIARAAQAKAAAFALQADAKgBAXIAAF5QABAYgDAKQgFALgKAAIgRAAQgJAAgFAHgAyyIfQgHAHABAKQgBAOAJAFQAJAGAWAAICcAAQAYAAAJgGQAJgFAAgOQAAgKgHgHQgGgGgKAAIgTAAQgMAAgGgMQgCgFAAgbIgBiLQAAgZAJgFQAEgEAeAAIBGAAQAaAAAIAEQAHADACANIABAFQAEAWATABQANgBAGgIQAFgKAAgWIAAhHQAAgWgFgJQgGgJgNAAQgUAAgDAVIgBAGQgBAMgIAEQgHADgbAAIhGAAQgeAAgEgDQgJgFAAgaIAAhlQABghAIgJQAJgJAiAAIBtAAQAgAAANAEQAOAFAGAPQAFAOADAFQAIAOAOAAQAMAAAFgJQAGgJgEgQIgMg8QgFgUgZgBIlwAAQgWABgIAFQgJAGAAAOQgBAJAHAHQAHAHAIAAIASAAQAEAAAEAEQAEADABAGQAEAKAAAXIAAF8QAAAXgDAJQgEAMgKAAIgSAAQgJAAgGAGgACorXQACAKgJADQgpAOgmATQgmATgZASQg5AoggBCQgfBEAABaQgBCLBPBTQBOBUCEAAQCHAABQhVQBPhUAAiOQAAilhohNQg7gsg4AGQghAEgFAUQgFATAbAKQA2AUAZA8QAXA3ABBfQAABxgrBBQgrBChKAAQhLAAgphBQgrg/AAhyQAAhQAQg0QASg+AwgvQAegdBHgjQA9gfAigrQATgZABgVQACgTgQgEQgMgEgNANIgZAWQguAeg4gRQgvgPgjgoQgcgggogIQgcgGgfAHQgLADgEgHQgCgHAKgIQAbgVArACQAvACAfAcQAdAbAhAPQAjARAagGQARgDAAgOQABgOgTgHQgegLgng1Qgmg0g0gQQhOgWhLA9QhDA3gXBWQgGAXAMALQAMALAUgKQA7gZAuAWQAJAEAhAVQAcARAWAJQAsARA7gLIAGAAQAIAAACAHgAvDlPIBJDYQAHAXALAJQALAKATAAQATAAALgLQAKgLAJggICImzQAGgWAHgJQAIgJALgCQAkgEgBAwIAAF+QAAAbgCAHQgBAEgFADQgEADgFAAIgQAAQgJAAgHAHQgGAHgBAJQAAAOAJAGQAJAFAVAAICbAAQAVAAAIgFQAHgFABgOQAAgKgGgHQgGgHgJAAIgQAAQgLAAgFgKQgCgKAAgYIAAiBQgBgeAGgGQAFgHAYABIBzAAQAYgBAHAIQACAEABAGIAAAeIAAB8QAAAbgCAHQgGAKgJAAIgRAAQgIAAgHAHQgGAHAAAJQgBAOAJAGQAIAFAWAAICaAAQAWAAAJgFQAJgGAAgOQAAgJgHgHQgGgHgKAAIgRAAQgEAAgFgDQgEgDgBgEQgEgKAAgYIAAl+QAAgXAEgKQABgEAEgDQAFgEAEAAIARAAQAKABAGgHQAHgHAAgKQgBgOgIgFQgJgGgWAAIiaAAQgWAAgJAGQgJAFABAOQgBAKAHAHQAGAHAKgBIARAAQAKAAAFALQACAGAAAbIAABpIAAAeQgBAHgCADQgHAHgYAAIhzAAQgYAAgFgGQgGgHABgdIAAhuQAAgYACgJQAFgLALAAIAQAAQAJABAGgHQAGgHAAgKQAAgOgIgFQgIgGgVAAIkmAAQgRAAgIAGQgIAFAAANQAAAWAcABQAeAEAAATQAAAIgEAMIheE7QgCAFgEABQgEAAgCgGIhfksQgIgZgBgLQAAgMAHgEQAFgFARgCQAcgFgBgSQAAgXgcAAIinAAQgdAAgBAaQABAJAFAFQAGAFANADQAOAFAHADQAHAFADAKIAmBtQAHAYgJAZIg+C3QgCAFgEAAQgFABgCgFIh0lIQgCgLAAgIQAAgKAGgFQAGgEAOgCQARgBAGgGQAIgEgBgLQAAgXgcAAIiuAAQgdAAAAAWQAAALAFAEQAFAGANACQAVAFAHAGQAHAIAJAaICnG/QAJAXALAKQAKAJATAAQAQAAAMgJQAIgIAJgZIBOjYQABgGAEAAQAFAAABAGgAOkiCQgGAHAAAJQAAAOAJAGQAHAFAWABIFigBQAaAAAFgVIANhCQADgQgFgJQgEgJgNABQgPAAgHAPIgIAQQgPAggvAAIhUAAQgkAAgPgGQgKgEgDgLQgDgLAAgiIAAhsQAAgZAIgFQAEgDAfAAIAmAAQAbAAAHADQAIADACANIAAAFQAEAXAUAAQANAAAGgJQAEgJAAgWIAAhIQAAgVgEgJQgGgKgNAAQgUAAgEAWIAAAFQgCANgHADQgIADgbAAIgmAAQgfAAgEgCQgIgGAAgaIAAhkQAAgiAIgJQAJgIAjgBIBQAAQAfABANAEQAPAFAFAPQAGAQADACQAHAOAOAAQANAAAEgJQAGgJgEgQIgMg7QgFgVgZAAIlTAAQgVAAgJAGQgJAFAAAOQAAAJAGAIQAIAGAIAAIARAAQAEAAAEAEQAEAEACAFQADAIAAAaIAAF7QAAAagDAIQgCAEgDADQgEAEgFAAIgRAAQgJAAgGAGgAHyiCQgGAHAAAJQAAAOAJAGQAIAFAVAAIE/AAQAaAAAFgVIAMhCQAEgQgFgJQgFgJgMABQgPAAgIAPIgHAQQgQAgguAAIgxAAQgZAAgMgCQgMgBgGgFQgIgFgCgJQgCgJAAgdIAAllQABgbACgFQADgMAOAAIATAAQAJABAHgHQAGgHABgKQgBgOgIgFQgKgGgXAAIicAAQgWAAgJAGQgJAFAAAOQAAAKAHAHQAGAHAKgBIARAAQALAAADAMQADAHAAAZIAAGBQAAAXgDAIQgBAEgEADQgFAEgEAAIgRAAQgJAAgGAGg");
	this.shape.setTransform(0,0,0.14,0.14);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#FFFFFF").s().p("AgYAaQgKgLAAgPQAAgOAKgKQAKgLAOABQAPgBAKALQAKAKAAAOQAAAPgKALQgKAJgPABQgOgBgKgJgAAWAYIgPgVQANgBAAgNQAAgPgRAAIgTAAIAAAyIAJAAIAAgVIAFAAIAOAVIAKAAg");
	this.shape_1.setTransform(18.3,8.3,0.14,0.14);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#FFFFFF").s().p("AgrAiQgFAAgEgDQgEgDAAgFIAAgtQAAgLANAAIA+AAQARAAAKAJQALAJAAAPQAAAQgLAJQgKAJgRAAg");
	this.shape_2.setTransform(-1.6,11.9,0.14,0.14);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#FFFFFF").s().p("AgJAHIAAgNIAIAAQALAAAAAGQAAAHgNAAg");
	this.shape_3.setTransform(18.3,8.1,0.14,0.14);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#FFFFFF").s().p("AhvCsQgog9AAhtQAAhtAog/QAog/BHAAQBGAAAoA/QAqBAAABqQAABrgpBAQgpA/hFAAQhIAAgog+g");
	this.shape_4.setTransform(-6.8,4.2,0.14,0.14);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#FFFFFF").s().p("AgYAfQgIAAADgIIAZgyQABgDADAAQADAAACADIAZAzQABADgCACQAAAAgBABQAAAAgBAAQAAABgBAAQAAAAgBAAg");
	this.shape_5.setTransform(-6.2,12.3,0.14,0.14);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f("#FFFFFF").s().p("AgtDtQgngDgNgHQgVgLAAghIAAljQAAghAKgMQAKgLAcgFIAdgDQBLAAAqA/QArA/AABvQAABxgrA/QgqA8hGAAIgJAAg");
	this.shape_6.setTransform(9,4.2,0.14,0.14);

	this.shape_7 = new cjs.Shape();
	this.shape_7.graphics.f("#FFFFFF").s().p("AhvCsQgog9AAhtQAAhtAog/QApg/BGAAQBFAAAqA/QApBAAABqQAABrgpBAQgpA/hGAAQhGAAgpg+g");
	this.shape_7.setTransform(1,4.2,0.14,0.14);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_7},{t:this.shape_6},{t:this.shape_5},{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).wait(1));

}).prototype = getMCSymbolPrototype(lib.whitelogouse, new cjs.Rectangle(-24.5,-24.5,49,49), null);


(lib.trynewflavors = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AgGAvIgKgBIgCABIgEABIgBgBIgCAAQgDgDgDgHQgDgIAAgHQABgDABgBQABgBAAAAQABgBAAAAQAAAAABAAQAAAAABAAQAFgBAEAIIADAFQADAEAFACQAEACAFAAQAGAAADgDQAEgDAAgFQAAgHgOgIIgGgCQgOgIgFgFQgFgGAAgIQAAgNAIgHQAJgIANABIAGAAIAGABIAEgBIADgBQAFAAAEAHQAEAHAAAIQAAADgCADQAAAAAAAAQgBAAAAABQgBAAAAAAQgBAAAAAAIgFgBIgEgHQgEgFgEgDQgDgCgGAAQgDAAgEADQgDADAAAFQAAAEADAEQADADALAFIABABQAZAMABAOQgBANgJAIQgKAJgPAAg");
	this.shape.setTransform(64.8,2.1);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#FFFFFF").s().p("AgaAtQgFgBAAgEQAAgDAEgCIACgBQADgBABgDIABgLIAAgFIAAgIIAAgFQAAgQgBgFQgBgGgCgBIgEgBQgFgCgBgDQAAAAABgBQAAAAAAgBQAAAAABgBQAAAAAAgBIAGgCIAMgFIAIgCQAFAAABANIAAACIAAAAQAFgHAFgEQAFgEAFAAQAHAAAEAEQADAEABAGQAAAGgEAFQgCADgFAAIgFgBIgEgCIgCgFIgCgCQgHAAgCAJQgCAJAAAaQAAAJABADQABAEACACIAEABQAGACgBAEQAAADgEABQgFACgMAAQgOAAgEgCg");
	this.shape_1.setTransform(57.6,2.1);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#FFFFFF").s().p("AghAiQgNgNAAgVQAAgTAOgOQAOgOATAAQAUAAANANQAMANAAAUQAAAUgNAPQgNAOgUAAQgTAAgOgOgAgRgaQgFAHAAAMQAAASAHAMQAIAMALAAQAIAAAGgIQAFgHABgNQgBgQgHgNQgIgMgKAAQgJAAgGAIg");
	this.shape_2.setTransform(48.8,2.1);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#FFFFFF").s().p("AgJAmQgFgJgNgdIgGgOQgGgRgEgCIgDgBQgFgCAAgEQAAgDAEgCQAFgBAPAAQANAAAEABQAEACAAADIAAADIgCACIgDABQgBABgBAAQAAAAgBABQAAAAAAABQAAAAgBABIACAHIAHASIAHARQACAEABAAIAEgDIADgIIAKgWIADgMIAAgDIgDgCIgCgBQgEgCAAgDQAAgDAEgCQAFgBALAAQAJAAAEABQAEACAAADQAAAEgFABIgDABQgEACgIASIgDAGIgDAIQgVAvgFAAQgEAAgFgJg");
	this.shape_3.setTransform(38.9,2.3);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#FFFFFF").s().p("AAQArIgFgFIgEACQgKAIgMAAQgNAAgIgIQgIgIAAgMQAAgPAKgHQALgIATAAQAEAAACABQABABAAAAQAAAAABABQAAAAAAABQAAABAAABQAAAEgFAAQgJAAgGAFQgFAEAAAIQAAAHAFAFQAEAEAIAAQAIAAAEgEQAEgEAAgJIAAgiQAAgIgDgFQgEgEgFAAQgFAAgEACQgEACgDAEIgCACQgGAHgGAAQgEAAgCgCQgCgCAAgEQAAgJALgGQAKgGARAAQAJAAAIADQAHADAEAFQADADABAGIABATIAAAcIABAIIACADIADABQAGABAAADQAAAFgGADQgGAEgIAAQgEAAgFgFg");
	this.shape_4.setTransform(29.4,2.1);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#FFFFFF").s().p("AgPBCQgEgCAAgEQAAgDAEgBIAEgDQACgBABgGIAAgSIAAgOIAAgRIAAgHQAAgXgBgGQgBgHgBgBIgGgCQgGgCAAgDQAAgBAAAAQAAgBABAAQAAgBAAAAQAAAAABgBIAIgEIANgDIAIgBQABAAAAAAQABAAAAAAQABAAAAABQABAAAAAAQABACAAAEIAAAHIgBBBIAAAfQABAHABACIAGADQAEABAAAEQAAADgFACQgEABgMAAQgNAAgFgBg");
	this.shape_5.setTransform(21.7,0);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f("#FFFFFF").s().p("AguBBQgFgCAAgDQAAgEAFgCIAGgDIACgQIABgjIgBghQgBgOgBgCIgGgDQgFgDAAgDQAAgDAFgCQAEgBAQAAIA3AAIAJgBIAFgBIACABIABABIAEAKIACAKQAAAEgCADQgBACgDAAQgDAAgEgHIgDgEQgCgDgEgBQgEgBgGgBIgNAAIgMABQgEACgCACQgCABAAAHIgBARIAAAHQAAAFABABQAAAAAAAAQAAAAABABQAAAAABAAQAAAAABAAIAOAAQAIAAACgCQADgCABgGIAAgBQACgKAFAAQAEAAABAEQACAFAAATQAAAQgCAEQgBAGgEAAQgFAAgCgKIAAgBQgBgHgDgBQgCgCgIgBIgOAAQAAAAgBABQAAAAgBAAQAAAAgBAAQAAABAAAAQgBABAAAGIAAAHIABAaQAAAFACACIAEACQAGACAAAEQAAADgGACQgFACgOAAQgPAAgFgCg");
	this.shape_6.setTransform(13.9,0.1);

	this.shape_7 = new cjs.Shape();
	this.shape_7.graphics.f("#FFFFFF").s().p("AAFAKIgKgcQgFgNgEgCIgDgBQgGgCABgEQgBgDAFgCQAEgBAOAAQANAAAEABQAFACAAADIAAADIgCACIgEABQAAABgBAAQgBAAAAABQgBAAAAABQAAAAAAABIABAGIAIATIAIARQACAEABAAQAAAAABAAQAAgBABAAQAAAAAAgBQABAAAAgBIAEgIIAKgWQAEgJgBgDIgBgDIgCgCIgCgBQgEgCgBgDQABgDAEgCQAEgBALAAQAKAAAEABQAEACgBADQABAEgFABIgEABQgEADgIATIgCAEIgEAIQgUAvgHAAQgGAAgQglgAg1AFIgDgFIgGgPQgFgQgFgCIgDgBQgEgCgBgEQAAgDAFgCQAFgBAOAAQANAAAEABQAEACAAADIAAADIgCACIgCABQgBABgBAAQgBAAAAABQgBAAAAABQAAAAAAABIACAHIAGASIAIAQQACAFACAAQACAAADgGIADgGIADgDIACgBQABAAAAAAQABAAAAAAQABAAAAABQABAAAAAAQAAABABAAQAAAAAAABQAAAAAAABQABAAAAABQgBACgCAFIgOAcQgEAHgEAAQgGAAgSgqg");
	this.shape_7.setTransform(-4.1,2.3);

	this.shape_8 = new cjs.Shape();
	this.shape_8.graphics.f("#FFFFFF").s().p("AgdAjQgNgOAAgUQAAgUAOgOQANgOAUAAQARAAALAKQAKAKAAASQAAAFgCACQgCACgGAAIgiAAQgBAAgBAAQgBAAAAgBQgBAAAAAAQgBAAAAgBQAAAAgBgBQAAAAAAgBQgBAAAAgBQAAAAAAgBQAAAAAAgBQAAAAABgBQAAAAAAgBQABAAAAAAQAAgBABAAQAAAAABAAQAAgBABAAQABAAABAAIASAAIAEAAIACgDQgBgJgFgGQgHgGgIAAQgKAAgFAKQgFAJAAANQAAAOAHAKQAHALALAAQAGAAAFgCQAFgBAEgDIADgDQAFgEACAAQABAAAAAAQABAAAAABQABAAAAAAQABAAAAABQAAAAABAAQAAABAAAAQAAAAAAABQABAAAAABQgBACgCADIgGAGQgIAHgIADQgHADgJAAQgSAAgNgNg");
	this.shape_8.setTransform(-16.6,2.1);

	this.shape_9 = new cjs.Shape();
	this.shape_9.graphics.f("#FFFFFF").s().p("AAIAZIgCgDIgUgZIgSgYIgIgIIAAAGIAAAMIAAAJQAAAoABAKQABAKACAAQADAAADACQADACgBADQAAAEgEABQgEABgLAAQgLAAgEgBQgFgBABgEQAAgEAEgCIAGgDQACgCAAgNIAAgjIAAgjQAAgNgCgCIgGgEQgEgBAAgDQAAgFADgBQAFgBALAAIAKAAIADABIAOARIASAXIAUAYIAOARIAKALIAAgDIAAgIIgBgsIgBgWIgBgCIgDgBIgGgDIgBgDQAAgEAEgCQADgBANAAIAPABQADACABAEIgBADIgEACIgCAAQgEACAAACIgCAWIgBA2IAAARIABAMQAAAHgBABQAAABgBAAQAAAAAAABQgBAAAAAAQgBAAAAAAQgKAAghgpg");
	this.shape_9.setTransform(-28.5,0.2);

	this.shape_10 = new cjs.Shape();
	this.shape_10.graphics.f("#FFFFFF").s().p("AgqA8QgEgDAAgGQAAgFADgDQAEgDAEAAIAEAAIADACIACAEQADADACAAQAEAAAFgGQAFgHAAgHQAAgIgGgPIgCgCIgOgfIgIgSQgCgDgGgCIgEgDIgBgDQAAgEAFgCQAFgBANAAQANAAAFABQAFACAAADIgBADIgCACIgDABQgBABgBAAQAAAAgBABQAAAAAAABQAAAAAAAAIABAHIAIATIAGARQACAEACAAQABAAACgEIAGgPIAHgSIACgJQAAgCgGgDQgEgDAAgCQAAgEADgBQAFgBAKAAQALAAAEABQAEACAAADQAAAEgGABIgDABQgFADgGAQIgDAHIgMAcQgOAmgKAMQgJALgNAAQgHAAgFgEg");
	this.shape_10.setTransform(-45.3,4);

	this.shape_11 = new cjs.Shape();
	this.shape_11.graphics.f("#FFFFFF").s().p("AgaAtQgFgBAAgEQAAgDAEgCIACgBQADgBABgDIABgLIAAgFIAAgIIAAgFQAAgQgBgFQgBgGgCgBIgEgBQgFgCgBgDQAAAAABgBQAAAAAAgBQAAAAABgBQAAAAAAgBIAGgCIAMgFIAIgCQAFAAABANIAAACIABAAQAFgHAEgEQAFgEAFAAQAHAAAEAEQAEAEAAAGQAAAGgEAFQgCADgGAAIgEgBIgEgCIgCgFIgCgCQgHAAgCAJQgCAJAAAaQAAAJABADQABAEACACIAEABQAGACgBAEQAAADgEABQgGACgLAAQgOAAgEgCg");
	this.shape_11.setTransform(-53.2,2.1);

	this.shape_12 = new cjs.Shape();
	this.shape_12.graphics.f("#FFFFFF").s().p("AgTBBQgFgCAAgEQAAgDAFgCIAGgDQABgCABgPIAAgqIAAgZIgBgOQAAgBAAAAQAAgBgBAAQAAgBAAAAQgBAAAAAAIgFgBIgEAAQgGAAgEABQgEACgCADIgDAGIgDAHIgCADIgEABQAAAAgBAAQAAgBgBAAQAAAAgBgBQAAAAgBgBIAAgIQgBgMADgHQADgIAEAAIABAAQAIACALAAIA0AAQAMAAAHgCIABAAQAEAAADAIQADAHAAAMQAAAGgBACQAAABgBAAQAAABgBAAQAAAAgBABQAAAAgBAAIgEgBIgCgDIgCgHIgDgGQgDgDgDgCQgEgBgGAAIgFAAIgEABQgBAAAAAAQAAAAgBABQAAAAAAABQAAAAAAABIgBAPIgBAYIABAqQABAPABACIAFADQAGACAAADQgBAEgFACQgFACgOAAQgOAAgFgCg");
	this.shape_12.setTransform(-62.8,0.1);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_12},{t:this.shape_11},{t:this.shape_10},{t:this.shape_9},{t:this.shape_8},{t:this.shape_7},{t:this.shape_6},{t:this.shape_5},{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).wait(1));

}).prototype = getMCSymbolPrototype(lib.trynewflavors, new cjs.Rectangle(-70.8,-12.8,141.7,25.8), null);


(lib.tablelargemobile = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.instance = new lib.largemobiletable();
	this.instance.parent = this;
	this.instance.setTransform(-160,-50);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

}).prototype = getMCSymbolPrototype(lib.tablelargemobile, new cjs.Rectangle(-160,-50,320,100), null);


(lib.noveleventwelve = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AAcA7QgBAAAAAAQAAgBgBAAQAAgBAAAAQAAgBAAAAIg/AAQgFAAgBgBQgBgBAAAAQAAAAgBgBQAAAAAAgBQAAAAAAgBQAAgEAMgLIALgKQAYgYAFgJQAHgKgBgJQAAgIgEgGQgFgFgHAAQgGAAgEACQgFADgFAFIgFADQgEAGgDAAQgBAAgBAAQAAAAgBAAQAAgBgBAAQAAAAgBAAQAAgBAAAAQAAgBgBAAQAAgBAAAAQAAgBAAgBIABgFIAFgGQAIgIAKgFQAJgEALAAQAQAAAKAJQALAIgBAOQAAAJgEAIQgEAIgKAIIgQAPIgQAPIgBABIAAABIABABIACAAIAcAAIAIgBQAAAAABAAQAAgBABAAQAAAAABgBQAAAAABgBIACgEQAEgHAEAAQABAAAAAAQABAAAAAAQABABAAAAQAAAAABAAQAAABAAAAQAAABABAAQAAABAAAAQAAABAAABIgBAJIgEALIgFAKQgDADgCAAQgBAAAAAAQgBAAAAAAQgBgBAAAAQAAAAAAgBg");
	this.shape.setTransform(40.2,1.1);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#FFFFFF").s().p("AAAA6QgUAAgFgBQgEgBAAgEQAAgEAIgBIAHgCIADgCIABgEIABgNIAAgqIAAgHIAAgFQgBgHAAgBQgBgBAAAAQgBgBAAAAQgBAAAAAAQgBAAgBAAIgEAAIgFAAIgEgBQAAAAAAAAQAAgBgBAAQAAAAAAgBQAAAAAAgBQAAgCACgCIAKgFIAQgFIAKgBQAFAAACABQAAABAAAAQABABAAAAQAAABAAAAQAAABAAAAQAAADgDADIgBABQgCABAAAHIgBAjIABAYIAAAQIABAFIADACIAHACQAIABAAAEQAAAEgFABQgEABgSAAg");
	this.shape_1.setTransform(30.3,0.9);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#FFFFFF").s().p("AgVAIIgCgDIABgEIADgFIACgDQABgBAEAAIAEAAIAIAAIAQAAIACgBIAEABQAAABABAAQAAAAAAABQAAAAAAABQABAAAAABQAAAEgEAFQgDAEgDAAIgFAAIgFAAIgUAAIgCABQAAAAgBAAQAAAAgBgBQAAAAgBAAQAAAAAAgBg");
	this.shape_2.setTransform(22.1,2);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#FFFFFF").s().p("AAAA6QgUAAgEgBQgFgBAAgEQAAgEAHgBIAIgCIADgCIABgEIAAgNIAAgqIAAgHIAAgFQAAgHgBgBQAAgBAAAAQgBgBAAAAQgBAAAAAAQgBAAgBAAIgEAAIgEAAIgFgBQAAAAAAAAQAAgBgBAAQAAAAAAgBQAAAAAAgBQAAgCACgCIAKgFIAQgFIALgBQADAAACABQABABAAAAQABABAAAAQAAABAAAAQAAABAAAAQAAADgDADIgBABQgCABAAAHIAAAjIAAAYIAAAQIABAFIADACIAHACQAIABAAAEQAAAEgFABQgEABgSAAg");
	this.shape_3.setTransform(14,0.9);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#FFFFFF").s().p("AAAA6QgUAAgEgBQgFgBAAgEQAAgEAHgBIAIgCIADgCIABgEIABgNIAAgqIAAgHIAAgFQAAgHgCgBQAAgBAAAAQgBgBAAAAQgBAAAAAAQgBAAgBAAIgEAAIgEAAIgEgBQgBAAAAAAQAAgBgBAAQAAAAAAgBQAAAAAAgBQAAgCADgCIAJgFIAQgFIALgBQADAAACABQABABAAAAQABABAAAAQAAABAAAAQABABAAAAQAAADgEADIgCABQgBABAAAHIAAAjIAAAYIAAAQIABAFIADACIAHACQAIABAAAEQAAAEgEABQgFABgSAAg");
	this.shape_4.setTransform(3.8,0.9);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#FFFFFF").s().p("AgJAKQgEgEAAgGQAAgFAEgEQAEgEAFAAQAGAAAEAEQAEAEAAAFQAAAGgEAEQgEAEgGAAQgFAAgEgEg");
	this.shape_5.setTransform(-8.9,5.5);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f("#FFFFFF").s().p("AgJAmQgGgJgMgdIgGgOQgGgRgEgCIgDgBQgFgCAAgEQAAgDAFgCQAEgBAPAAQAMAAAFABQAEACAAADIgBADIgBACIgDABQgBABgBAAQAAAAgBABQAAAAAAABQgBAAAAABIADAHIAGASIAHARQACAEACAAIADgDIADgIIAKgWIAEgMIgBgDIgDgCIgCgBQgEgCAAgDQAAgDAEgCQAEgBAMAAQAJAAAEABQAEACAAADQAAAEgFABIgDABQgEACgIASIgDAGIgDAIQgVAvgFAAQgEAAgFgJg");
	this.shape_6.setTransform(-16.1,2.3);

	this.shape_7 = new cjs.Shape();
	this.shape_7.graphics.f("#FFFFFF").s().p("AghAiQgNgNABgVQAAgTANgOQAOgOATAAQAUAAANANQAMANAAAUQAAAUgNAPQgOAOgTAAQgTAAgOgOgAgRgaQgFAHAAAMQAAASAHAMQAIAMAKAAQAJAAAGgIQAGgHAAgNQgBgQgHgNQgIgMgKAAQgJAAgGAIg");
	this.shape_7.setTransform(-26,2.1);

	this.shape_8 = new cjs.Shape();
	this.shape_8.graphics.f("#FFFFFF").s().p("AAJAZIgDgDIgUgZIgTgYIgHgIIgBAGIAAAMIAAAJQAAAoABAKQACAKADAAQACAAADACQACACABADQgBAEgEABQgFABgKAAQgLAAgEgBQgFgBAAgEQABgEAEgCIAGgDQABgCABgNIABgjIgBgjQgBgNgBgCIgGgEQgEgBgBgDQABgFAEgBQADgBAMAAIAKAAIADABIAOARIASAXIAUAYIAOARIAKALIAAgDIAAgIIgBgsIgBgWIgCgCIgCgBIgGgDIgBgDQAAgEAEgCQADgBANAAIAPABQADACAAAEIgBADIgDACIgCAAQgEACgBACIgBAWIgBA2IAAARIABAMQAAAHgBABQAAABgBAAQAAAAAAABQgBAAAAAAQgBAAAAAAQgKAAgggpg");
	this.shape_8.setTransform(-38.3,0.2);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_8},{t:this.shape_7},{t:this.shape_6},{t:this.shape_5},{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).wait(1));

}).prototype = getMCSymbolPrototype(lib.noveleventwelve, new cjs.Rectangle(-47.5,-12.8,95.1,25.8), null);


(lib.mainbutton = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#006F46").s().p("EgQFAzRMAAAhmhMAgLAAAMAAABmhg");
	this.shape._off = true;

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(3).to({_off:false},0).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = null;


(lib.greyrectangle = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f().s("#999999").ss(1,1,1).p("A4cnQMAw5AAAIAAOhMgw5AAAg");
	this.shape.setTransform(0,0,1.019,1.065);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = getMCSymbolPrototype(lib.greyrectangle, new cjs.Rectangle(-160.5,-50.5,321,101), null);


(lib.foryourfeast = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AgJAcQgBAAAAAAQAAgBAAAAQgBAAAAgBQAAAAAAAAIACgEIACgCIAFgKIACgHIgBgCIgDgBQgEgCgDgDQgCgEAAgFQAAgGAEgEQAEgEAFAAQAGAAAEAGQAEAFAAAIQAAAGgDAGQgCAHgGAJIgEAIIgEACIgEgBg");
	this.shape.setTransform(58.8,6.9);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#FFFFFF").s().p("AgEA3QgEgCgEgDQgDgDgCgFQgBgEAAgOIAAgwIgIAAIgDgBIAAgDIAAgCQAAgCAJgJIADgDIAEgDQAKgJADAAIACABIABACIAAARIAVAAIADABIAAAEIAAACIAAADIgDACIgTAAIgBABIgBACIAAAsQAAAMACADQACADAFAAIAHgBIAHgCIADABQAAAAABABQAAAAAAAAQAAABAAAAQABABAAAAQAAAFgIAFQgIAFgKAAQgFAAgEgCg");
	this.shape_1.setTransform(52.9,1.3);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#FFFFFF").s().p("AgGAvIgKgBIgDABIgCABIgCgBIgCAAQgDgDgCgHQgEgIAAgHQAAgDACgBQAAgBABAAQAAgBABAAQAAAAABAAQAAAAABAAQAFgBAEAIIADAFQADAEAEACQAFACAFAAQAGAAADgDQAEgDAAgFQAAgHgOgIIgGgCQgOgIgFgFQgFgGAAgIQAAgNAIgHQAJgIANABIAGAAIAGABIAEgBIADgBQAEAAAEAHQAFAHAAAIQAAADgBADQgBAAAAAAQgBAAAAABQgBAAAAAAQgBAAgBAAIgDgBIgGgHQgDgFgEgDQgDgCgGAAQgEAAgDADQgDADAAAFQAAAEADAEQADADALAFIABABQAaAMgBAOQABANgKAIQgKAJgPAAg");
	this.shape_2.setTransform(45.6,2.1);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#FFFFFF").s().p("AAQArIgFgFIgEACQgKAIgMAAQgNAAgIgIQgIgIAAgMQAAgPAKgHQALgIATAAQAEAAACABQABABAAAAQAAAAABABQAAAAAAABQAAABAAABQAAAEgFAAQgJAAgGAFQgFAEAAAIQAAAHAFAFQAEAEAIAAQAIAAAEgEQAEgEAAgJIAAgiQAAgIgDgFQgEgEgFAAQgFAAgEACQgEACgDAEIgCACQgGAHgGAAQgEAAgCgCQgCgCAAgEQAAgJALgGQAKgGARAAQAJAAAIADQAHADAEAFQADADABAGIABATIAAAcIABAIIACADIADABQAGABAAADQAAAFgGADQgGAEgIAAQgEAAgFgFg");
	this.shape_3.setTransform(37,2.1);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#FFFFFF").s().p("AgdAjQgNgOAAgUQAAgUAOgOQAMgOAVAAQARAAALAKQAKAKAAASQAAAFgCACQgCACgGAAIgiAAQgBAAgBAAQgBAAAAgBQgBAAAAAAQgBAAAAgBQAAAAgBgBQAAAAAAgBQgBAAAAgBQAAAAAAgBQAAAAAAgBQAAAAABgBQAAAAAAgBQABAAAAAAQAAgBABAAQAAAAABAAQAAgBABAAQABAAABAAIARAAIAGAAIABgDQgBgJgGgGQgFgGgJAAQgKAAgFAKQgFAJgBANQABAOAHAKQAHALALAAQAGAAAFgCQAFgBAEgDIAEgDQAEgEACAAQABAAAAAAQABAAAAABQABAAAAAAQABAAAAABQAAAAABAAQAAABAAAAQAAAAAAABQABAAAAABQgBACgCADIgGAGQgIAHgIADQgHADgJAAQgSAAgNgNg");
	this.shape_4.setTransform(27.2,2.1);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#FFFFFF").s().p("AguBBQgFgCAAgDQAAgEAFgCIAGgDIACgQIABgjIgBghQgBgOgBgCIgGgDQgFgDAAgDQAAgDAFgCQAEgBAQAAIA3AAIAJgBIAFgBIACABIABABIAEAKIACAKQAAAEgCADQgBACgDAAQgDAAgEgHIgDgEQgCgDgEgBQgEgBgGgBIgNAAIgMABQgEACgCACQgCABAAAHIgBARIAAAHQAAAFABABQAAAAAAAAQAAAAABABQAAAAABAAQAAAAABAAIAOAAQAIAAACgCQADgCABgGIAAgBQACgKAFAAQAEAAABAEQACAFAAATQAAAQgCAEQgBAGgEAAQgFAAgCgKIAAgBQgBgHgDgBQgCgCgIgBIgOAAQAAAAgBABQAAAAgBAAQAAAAgBAAQAAABAAAAQgBABAAAGIAAAHIABAaQAAAFACACIAEACQAGACAAAEQAAADgGACQgFACgOAAQgPAAgFgCg");
	this.shape_5.setTransform(16.9,0.1);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f("#FFFFFF").s().p("AgbAtQgEgBAAgEQAAgDAEgCIACgBQADgBABgDIABgLIAAgFIAAgIIAAgFQAAgQgBgFQgBgGgBgBIgFgBQgGgCAAgDQAAAAABgBQAAAAAAgBQAAAAABgBQAAAAABgBIAFgCIANgFIAIgCQAEAAABANIAAACIAAAAQAGgHAEgEQAFgEAGAAQAGAAAEAEQADAEAAAGQAAAGgCAFQgDADgFAAIgFgBIgEgCIgCgFIgCgCQgGAAgCAJQgDAJAAAaQAAAJABADQABAEADACIADABQAFACABAEQAAADgGABQgEACgNAAQgNAAgFgCg");
	this.shape_6.setTransform(3,2.1);

	this.shape_7 = new cjs.Shape();
	this.shape_7.graphics.f("#FFFFFF").s().p("AAUAvIgBgFIAAgGIgBgBIgDACIgBACQgFAEgFACQgFADgHAAQgHAAgFgDQgHgDgEgEQgEgFgCgIQgCgHAAgTIABgGIAAgHIAAgCQAAgHgBgCQgBgCgEgCIgDgBQgGgBAAgDQAAgBAAAAQABgBAAgBQAAAAAAAAQABgBAAAAIAJgEIAMgDIAKgCQAAAAABAAQAAABABAAQAAAAABAAQAAABAAAAIABAGIAAAEIgBAiQAAASAEAHQAEAHAJAAQAKAAAEgJQAFgKAAgVIAAgHQAAgHgBgCQgBgCgDgCIgEgBQgFgBAAgDQAAgBAAAAQAAgBAAgBQABAAAAAAQAAgBABAAIAIgEIAMgDIAKgCQAAAAABAAQABABAAAAQABAAAAAAQABABAAAAIABAGIAAAFIgBAlIAAAPIAAAHQABADAFACIABABQAGABAAADQAAABAAAAQAAABgBAAQAAABAAAAQgBABAAAAIgGADIgNAEIgJACIgEgBg");
	this.shape_7.setTransform(-6.3,2.1);

	this.shape_8 = new cjs.Shape();
	this.shape_8.graphics.f("#FFFFFF").s().p("AggAiQgNgNgBgVQAAgTAOgOQAOgOAUAAQATAAANANQANANAAAUQAAAUgOAPQgNAOgUAAQgTAAgNgOgAgRgaQgFAHAAAMQAAASAIAMQAHAMALAAQAIAAAGgIQAFgHAAgNQABgQgJgNQgHgMgKAAQgJAAgGAIg");
	this.shape_8.setTransform(-16.7,2.1);

	this.shape_9 = new cjs.Shape();
	this.shape_9.graphics.f("#FFFFFF").s().p("AgTBAQgEgCgBgDQAAgEAGgCIAEgCQADgCABgmIAAgIIgLgRIgSgcQgFgHgDgCIgFgCQgFgCAAgDQAAgEADgCQAFgBASAAQARAAAFABQAEACAAAEQAAADgHACIAAAAIgEACIgBAEIAFAIIARAcIAQgYQAFgIAAgDQAAAAAAgBQAAAAAAgBQgBAAAAgBQAAAAAAAAQgCgCgEgCIgEgCIgBgDQgBgEAEgCQAEgBAPAAQAPAAADABQAFACAAAEQgBADgFACIgHAEQgDADgJANIgXAjIABAQQAAAfADACIADACQAHACAAAEQAAADgGACQgEACgPAAQgOAAgFgCg");
	this.shape_9.setTransform(-27.7,0.2);

	this.shape_10 = new cjs.Shape();
	this.shape_10.graphics.f("#FFFFFF").s().p("AgaAtQgFgBAAgEQAAgDAEgCIACgBQADgBABgDIABgLIAAgFIAAgIIAAgFQAAgQgBgFQgBgGgCgBIgEgBQgFgCgBgDQAAAAABgBQAAAAAAgBQAAAAABgBQAAAAAAgBIAGgCIAMgFIAIgCQAFAAABANIAAACIABAAQAFgHAEgEQAFgEAFAAQAHAAAEAEQAEAEAAAGQAAAGgEAFQgCADgGAAIgEgBIgEgCIgCgFIgCgCQgHAAgCAJQgCAJAAAaQAAAJABADQABAEACACIAEABQAGACgBAEQAAADgEABQgGACgLAAQgOAAgEgCg");
	this.shape_10.setTransform(-42,2.1);

	this.shape_11 = new cjs.Shape();
	this.shape_11.graphics.f("#FFFFFF").s().p("AghAiQgNgNABgVQAAgTANgOQAOgOATAAQAUAAANANQAMANAAAUQAAAUgNAPQgOAOgTAAQgTAAgOgOgAgRgaQgFAHAAAMQAAASAHAMQAIAMAKAAQAJAAAGgIQAGgHAAgNQgBgQgHgNQgIgMgKAAQgJAAgGAIg");
	this.shape_11.setTransform(-50.8,2.1);

	this.shape_12 = new cjs.Shape();
	this.shape_12.graphics.f("#FFFFFF").s().p("AgZBCQgEgBAAgFQAAgCAEgCIACgBQABAAAAgBQABAAAAAAQABgBAAgBQAAAAAAgBIABgLIAAgJIAAgrIgKAAQAAAAgBAAQAAAAgBAAQAAAAAAgBQgBAAAAAAIgBgDIAAgDIABgDIADgBIAKAAIgBgHIAAgHQAAgOAIgHQAIgIAPAAQAKAAAGAFQAHAEAAAIQAAAEgCADQgDACgEAAQgDgBgCgBQgDgBgBgDIgCgDQgDgGgGgBQgDABgCACQgBACAAADIABALQACAIAAAGIANAAIADABIABADIAAADIgBADIgDABIgNAAIAAAuIABAPQABAEABABIAEACQAFACAAADQAAADgEACIgRABIgSgBg");
	this.shape_12.setTransform(-57.8,0);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_12},{t:this.shape_11},{t:this.shape_10},{t:this.shape_9},{t:this.shape_8},{t:this.shape_7},{t:this.shape_6},{t:this.shape_5},{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).wait(1));

}).prototype = getMCSymbolPrototype(lib.foryourfeast, new cjs.Rectangle(-63.2,-12.8,126.4,25.8), null);


(lib.findanevent = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AgPAqQgIgEgFgGIAJgIQADAFAFADQAGACAFAAIAFgBQADAAADgCIAEgFQABgCAAgEQAAgEgBgCIgFgFIgGgDIgHgCIgIgEQgEAAgDgDQgDgCgCgFQgCgDAAgHQAAgGADgEQACgFAFgDQAEgDAFgBIAJgCIAIABIAGACQAHACAEAFIgJAIQgCgDgFgCQgEgCgFAAIgFAAIgFADIgEAEQgCACAAAEQAAAEACACQABACACACIAGACIAGADIAIADQAFABADADQAEACACAEQADAFAAAGQAAAGgDAGQgCAEgEAEQgFADgFABIgKABQgIAAgHgCg");
	this.shape.setTransform(51.5,0.4);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#FFFFFF").s().p("AgYAqIAAhTIAMAAIAABJIAlAAIAAAKg");
	this.shape_1.setTransform(45.6,0.4);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#FFFFFF").s().p("AgFAqIAAhTIALAAIAABTg");
	this.shape_2.setTransform(40.4,0.4);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#FFFFFF").s().p("AAdAqIgJgUIgnAAIgJAUIgNAAIAlhTIAJAAIAlBTgAAQALIgQgnIgPAnIAfAAg");
	this.shape_3.setTransform(34.6,0.4);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#FFFFFF").s().p("AgFAqIAAhJIgbAAIAAgKIBBAAIAAAKIgbAAIAABJg");
	this.shape_4.setTransform(26.9,0.4);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#FFFFFF").s().p("AgbAqIAAhTIA1AAIAAAKIgpAAIAAAaIAnAAIAAAJIgnAAIAAAcIArAAIAAAKg");
	this.shape_5.setTransform(20.2,0.4);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f("#FFFFFF").s().p("AgkAqIAAhTIAdAAQAHAAAIACQAIADAGAFQAHAFAEAHQACAFACAEIABAKIgBAKQgCAFgCAEIgFAHIgGAGQgGAGgIACQgKADgFgBgAgZAgIAPAAQAIAAAFgCQAHgDAEgDQAGgFACgFIACgHIABgHIgBgGIgCgHQgCgGgGgEQgEgEgHgCQgFgCgIAAIgPAAg");
	this.shape_6.setTransform(12,0.4);

	this.shape_7 = new cjs.Shape();
	this.shape_7.graphics.f("#FFFFFF").s().p("AgFAqIAAhJIgbAAIAAgKIBBAAIAAAKIgbAAIAABJg");
	this.shape_7.setTransform(0.8,0.4);

	this.shape_8 = new cjs.Shape();
	this.shape_8.graphics.f("#FFFFFF").s().p("AAVAqIgshEIAAAAIAABEIgMAAIAAhTIAPAAIArBCIABAAIAAhCIAMAAIAABTg");
	this.shape_8.setTransform(-7.2,0.4);

	this.shape_9 = new cjs.Shape();
	this.shape_9.graphics.f("#FFFFFF").s().p("AgbAqIAAhTIA2AAIAAAKIgqAAIAAAaIAnAAIAAAJIgnAAIAAAcIArAAIAAAKg");
	this.shape_9.setTransform(-15.2,0.4);

	this.shape_10 = new cjs.Shape();
	this.shape_10.graphics.f("#FFFFFF").s().p("AgFAqIghhTIANAAIAZBEIAAAAIAahEIANAAIgiBTg");
	this.shape_10.setTransform(-22.9,0.4);

	this.shape_11 = new cjs.Shape();
	this.shape_11.graphics.f("#FFFFFF").s().p("AgbAqIAAhTIA1AAIAAAKIgqAAIAAAaIAoAAIAAAJIgoAAIAAAcIAsAAIAAAKg");
	this.shape_11.setTransform(-30.1,0.4);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_11},{t:this.shape_10},{t:this.shape_9},{t:this.shape_8},{t:this.shape_7},{t:this.shape_6},{t:this.shape_5},{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).wait(1));

}).prototype = getMCSymbolPrototype(lib.findanevent, new cjs.Rectangle(-36,-9.1,93.1,18.8), null);


(lib.ctarollovervideo = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#B63100").s().p("AocBXIAAitIQ5AAIAACtg");
	this.shape.setTransform(0,-1,1.048,1.372);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = getMCSymbolPrototype(lib.ctarollovervideo, new cjs.Rectangle(-56.7,-13,113.5,24), null);


(lib.ctarectangle = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#D63900").s().p("Ao2B4IAAjvIRuAAIAADvg");
	this.shape.setTransform(10.8,0);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = getMCSymbolPrototype(lib.ctarectangle, new cjs.Rectangle(-46,-12,113.5,24), null);


(lib.blackwideskyscraper = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#000000").s().p("EgRBA2FMAAAhsJMAiDAAAMAAABsJg");
	this.shape.setTransform(0,0,0.753,0.867);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = getMCSymbolPrototype(lib.blackwideskyscraper, new cjs.Rectangle(-82.1,-300,164.3,600.1), null);


(lib.atasteofwholefoods = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AABAoIgBAAIgFgBQAAgBAAAAQAAAAgBAAQAAgBAAAAQAAgBAAgBIAAg5QAAAAAAgBQAAAAAAAAQgBgBAAAAQAAAAAAgBIgEAAIgGgBIgGAAIgDABQgBAAAAAAQgBAAAAAAQgBgBAAAAQAAAAgBgBIAAgDIAAgDIAAgDIACgCIACAAIA2AAQAAAAAAAAQABAAAAAAQABAAAAAAQAAABAAAAIABADIAAADIgBACIgBADIgCABIgQAAIgCAAQgBABAAAAQAAAAgBABQAAAAAAABQAAAAAAABIAAA4IAAADIgDACg");
	this.shape.setTransform(100.7,-0.2);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#FFFFFF").s().p("AgaAnIgCgBIgCgCIAAhHQAAgBAAAAQAAAAAAgBQABAAAAAAQAAAAABAAIACgBIA2AAIACABIAAADIABACIAAADIgBADIgCACIgoAAIgCABIgBACIAAALIABACIADABIAZAAIACABIABADIAAADIAAACQAAABAAAAQAAABgBAAQAAABgBAAQAAABgBAAIgZAAIgDABIgBADIAAAMIAAADIAEABIAnAAQACABAAADIAAADIAAADIgBACIgBABg");
	this.shape_1.setTransform(94,-0.3);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#FFFFFF").s().p("AASAoIgDgBIgTgfIgCgBIgDgBIgEABQgBABAAAAQgBAAAAABQAAAAgBABQAAAAAAAAIAAAZIgBADIgDABIgDABIgDAAQgEAAAAgFIAAhJIACgBIACgBIADAAIACAAQAEAAABACIAAAaQAAAAAAAAQAAABABAAQAAAAAAAAQAAABABAAIADABQABAAAAAAQAAAAABAAQAAgBABAAQAAgBABAAIAVgbIABAAIACAAIADAAIACACIADACIABACIgBACIgTAWIgBACIAAACIAAACIABACIAZAhIAAABIAAABIgBACIgDACIgDACIgCAAg");
	this.shape_2.setTransform(86.4,-0.2);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#FFFFFF").s().p("AAUAoIgCAAIgCgBIgBgBIgNgVIgCgCIgDgBIgKAAIgDABQAAAAAAAAQgBAAAAABQAAAAAAABQAAAAAAAAIAAATQAAABAAAAQAAAAAAABQAAAAgBAAQAAAAAAABIgDABIgDAAIgDAAIgDgBQgBAAAAgBQAAAAAAAAQgBgBAAAAQAAgBAAgBIABhHIABgCIACgBIAhAAQAGAAAFACQAFACAEADQADADADAGQACAEAAAHQAAAGgDAEIgFAHIgGADQAAABgBAAQAAABgBAAQAAABAAAAQAAAAAAABIAAACIADAEIAEAGIAEAHIACADIgBADIgCACIgDABIgDAAgAgQgZQAAABAAAAQgBAAAAABQAAAAAAABQAAAAAAABIAAASQAAAAAAAAQAAABAAAAQAAABABAAQAAAAAAAAIAEABIAPAAIAGAAIAFgCQACgCABgDIABgFQAAgHgEgDIgFgDIgGgBIgPAAIgEABg");
	this.shape_3.setTransform(78.5,-0.2);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#FFFFFF").s().p("AAdAnIgEAAQgBAAAAAAQgBgBAAAAQgBAAAAgBQAAAAAAgBIgFgKIgBgCIgCgBIgaAAIgBABIgBABIgCAAIAAABIgFAKIgBACIgCABIgDAAIgCAAIgCAAIgCAAIgCgBIgBgBIAghKQAAAAABAAQAAgBAAAAQAAAAABAAQAAAAAAAAIACgBIADAAIADACIAfBJIAAABIgBACIgCAAIgDABgAgBgLIgBACIgBAEIgCAFIgCADIgCAEIAAABIAAACIACABIAPAAIACgBIAAgCIgBgDIgDgFIgCgHIgCgEIgCgBIAAAAg");
	this.shape_4.setTransform(70.3,-0.2);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#FFFFFF").s().p("AAaAnIgDAAQgBAAAAgBQgBAAAAAAQAAgBAAAAQAAgBAAAAIAAgjIgBgBIgCgBQAAAAgBAAQAAAAAAAAQAAABgBAAQAAAAAAAAIgNAUQAAAAgBABQAAAAAAABQgBAAAAAAQgBAAAAAAIgCgBIgCgBIgKgUQgBAAAAAAQAAAAgBgBQAAAAAAAAQgBAAAAAAIgCABIgBABIAAAjQAAABAAAAQAAABgBAAQAAAAgBABQAAAAgBAAIgFAAIgCAAIgBAAIgCgBIgBgCIAAhHQAAgBABAAQAAgBAAAAQABAAAAgBQAAAAABAAIAEAAIAEAAIABACIATAfQABADADAAIACgBIABgCIATgeQACgEAEAAIADABQABAAAAAAQABAAAAABQAAAAAAAAQABAAAAABIAABIIgBACIgCABIgDAAg");
	this.shape_5.setTransform(62.1,-0.2);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f("#FFFFFF").s().p("AgRAmQgJgEgFgFIgCgCIAAgBIABgDIADgDIACgBIADgBIAEABIAFADIAGAEQAEABAFAAIAGAAIAGgCIAFgEQABgCAAgEQABgDgDgBQgCgCgEgBIgIgCIgIgCIgJgCQgEgBgFgBQgDgDgCgDQgCgEAAgGQAAgHADgEQADgEAFgDQAEgDAGgCIAKgBIAIAAIAIACIAHAEIAGAEIABABIAAACIgBADIgCACIgDABIgDABIgCAAIgJgFQgFgCgFAAIgFAAIgFACIgFADQgBACAAADQAAAFAEABIAJADIALACIAMACQAGACAEAEQADAFABAHQAAAHgDAGQgEAEgFAEQgFADgGABIgLACQgJAAgIgDg");
	this.shape_6.setTransform(50.6,-0.2);

	this.shape_7 = new cjs.Shape();
	this.shape_7.graphics.f("#FFFFFF").s().p("AggAnIgDAAQgBAAAAgBQAAAAAAAAQgBgBAAAAQAAAAAAgBIAAhGQAAgBAAAAQAAgBABAAQAAAAAAgBQAAAAABAAIADgBIAdAAIAHABIAIACQAIACAFAGQAGAFADAHQACADABAFIABAHQAAAJgEAHIgEAHIgFAGIgGAEIgHAEQgIACgHAAgAgVgXIgBADIAAAqQAAABAAAAQAAAAABABQAAAAAAAAQAAAAABABIACABIAPAAQAEAAAFgCIAJgFIAGgIQACgFAAgGQAAgFgCgEQgCgFgEgDQgEgEgFgCQgFgBgEAAIgOAAIgEABg");
	this.shape_7.setTransform(42.6,-0.3);

	this.shape_8 = new cjs.Shape();
	this.shape_8.graphics.f("#FFFFFF").s().p("AgHAoIgIgCIgIgEIgGgFQgGgFgDgIIgCgIIgBgIIABgHIACgIQADgHAGgGIAGgFIAIgEIAIgCIAHgBIAJABIAHACQAIADAGAGQAGAGADAHQADAHAAAIIgBAIIgCAIQgDAIgGAFQgGAGgIADIgHACIgJABIgHgBgAgJgYQgFACgEAEQgEADgCAFQgCAFAAAFQAAAGACAFQACAFAEADIAJAGQAFACAEAAQAFAAAFgCQAFgCAEgEQADgDADgFQACgFAAgGQAAgFgCgFQgDgFgDgDQgEgEgFgCQgFgCgFAAQgEAAgFACg");
	this.shape_8.setTransform(33.1,-0.3);

	this.shape_9 = new cjs.Shape();
	this.shape_9.graphics.f("#FFFFFF").s().p("AgHAoIgIgCIgIgEIgGgFQgGgFgDgIIgCgIIgBgIIABgHIACgIQADgHAGgGIAGgFIAIgEIAIgCIAHgBIAJABIAHACQAIADAGAGQAGAGADAHQADAHAAAIIgBAIIgCAIQgDAIgGAFQgGAGgIADIgHACIgJABIgHgBgAgJgYQgFACgEAEQgEADgCAFQgCAFAAAFQAAAGACAFQACAFAEADIAJAGQAFACAEAAQAFAAAFgCQAFgCAEgEQADgDADgFQACgFAAgGQAAgFgCgFQgDgFgDgDQgEgEgFgCQgFgCgFAAQgEAAgFACg");
	this.shape_9.setTransform(23.9,-0.3);

	this.shape_10 = new cjs.Shape();
	this.shape_10.graphics.f("#FFFFFF").s().p("AgXAoIgCAAQgDAAgCgDIAAhJIACgCIACgBIA2AAIABABIABACIABACIAAADIgBADIgCADIgoAAIgCABIgBADIAAAKIABACQAAAAABABQAAAAAAAAQAAAAABAAQAAAAAAAAIAZAAIADABIABADIAAADIAAABIgBAEQAAAAgBAAQAAAAAAABQAAAAgBAAQAAAAgBAAIgYAAIgCABIgBAAIgBABIgBACIAAAcIgBACIgCABg");
	this.shape_10.setTransform(16.5,-0.2);

	this.shape_11 = new cjs.Shape();
	this.shape_11.graphics.f("#FFFFFF").s().p("AgaAnIgCgBIgCgCIAAhHQAAgBAAAAQAAAAAAgBQABAAAAAAQAAAAABAAIACgBIA2AAIACABIABADIAAACIAAADIgBADIgCACIgoAAIgCABIgBACIAAALIABACIADABIAZAAIACABIAAADIABADIAAACQAAADgDABIgZAAIgDABIgBADIAAAMIAAADIAEABIAnAAQADABAAADIAAADIAAADIgCACIgCABg");
	this.shape_11.setTransform(5.6,-0.3);

	this.shape_12 = new cjs.Shape();
	this.shape_12.graphics.f("#FFFFFF").s().p("AgbAoIgCgBIgBgCIAAhIIABgDIACgBIADAAIADAAIADAAIADAEIAAA3IAAACIABACQACADADAAIAjAAIADAAIABACIABACIAAADIgBAEQgBAAAAABQAAAAgBAAQAAABgBAAQAAAAgBAAg");
	this.shape_12.setTransform(-2,-0.3);

	this.shape_13 = new cjs.Shape();
	this.shape_13.graphics.f("#FFFFFF").s().p("AgHAoIgIgCIgIgEIgGgFQgGgFgDgIIgCgIIgBgIIABgHIACgIQADgHAGgGIAGgFIAIgEIAIgCIAHgBIAJABIAHACQAIADAGAGQAGAGADAHQADAHAAAIIgBAIIgCAIQgDAIgGAFQgGAGgIADIgHACIgJABIgHgBgAgJgYQgFACgEAEQgEADgCAFQgCAFAAAFQAAAGACAFQACAFAEADIAJAGQAFACAEAAQAFAAAFgCQAFgCAEgEQADgDADgFQACgFAAgGQAAgFgCgFQgDgFgDgDQgEgEgFgCQgFgCgFAAQgEAAgFACg");
	this.shape_13.setTransform(-10.7,-0.3);

	this.shape_14 = new cjs.Shape();
	this.shape_14.graphics.f("#FFFFFF").s().p("AAVAoIgDgCIAAgcIgBgDIgDgCIgaAAQAAAAgBABQAAAAgBAAQAAAAgBABQAAAAgBABIAAADIAAAbQAAAAgBAAQAAAAAAABQAAAAAAAAQgBAAAAAAIgDABIgDAAIgDAAIgDgBIgCgBIAAhKIACgDIADAAIADgBIACAAQAEAAACAEIAAAYIAAAEIADABIAaAAQABAAAAAAQABAAAAAAQABgBAAAAQAAAAABAAQAAgBAAAAQAAAAABgBQAAAAAAgBQAAAAAAgBIAAgYQAAgBABgBQAAAAABAAQAAgBABAAQAAAAABAAIAFAAIADAAIACADIAABKQAAAAAAABQAAAAgBAAQAAABgBAAQAAAAgBAAIgFAAg");
	this.shape_14.setTransform(-19.5,-0.2);

	this.shape_15 = new cjs.Shape();
	this.shape_15.graphics.f("#FFFFFF").s().p("AARAoIAAgCIgOggIgBgCIgCgBIgCABIgCACIgMAgIgBACIgBABIgBgBIgBgCIgCgFIgDgJIgFgLIgEgNIgGgLIgEgLIgDgIIgBgEIABgDIADgBIACgBIADAAIADABIACABIAOAlIACABIABABIACAAIABgCIAMgbIABgBIABAAIACAAIABACIAMAaIABACIACAAIACAAIABgCIAPglQACgCACAAIADAAIADABIACABIABACIgCAFIgCAIIgFALIgEALIgGANIgEALIgEAKIgCAEIgBACIgBABg");
	this.shape_15.setTransform(-29,-0.3);

	this.shape_16 = new cjs.Shape();
	this.shape_16.graphics.f("#FFFFFF").s().p("AgWAoIgEAAQgDAAgBgDIAAhJIACgCIACgBIA1AAIACABIACACIAAACIAAADIgBADIgDADIgmAAIgDABIgBADIAAAKIABACQAAAAABABQAAAAAAAAQAAAAABAAQAAAAABAAIAZAAIACABIAAADIAAADIAAABIAAAEQAAAAgBAAQAAAAAAABQAAAAgBAAQAAAAAAAAIgZAAIgBABIgCAAIgBABIgBACIAAAcIgBACIgCABg");
	this.shape_16.setTransform(-40.3,-0.2);

	this.shape_17 = new cjs.Shape();
	this.shape_17.graphics.f("#FFFFFF").s().p("AgHAoIgIgCIgIgEIgGgFQgGgFgDgIIgCgIIgBgIIABgHIACgIQADgHAGgGIAGgFIAIgEIAIgCIAHgBIAJABIAHACQAIADAGAGQAGAGADAHQADAHAAAIIgBAIIgCAIQgDAIgGAFQgGAGgIADIgHACIgJABIgHgBgAgJgYQgFACgEAEQgEADgCAFQgCAFAAAFQAAAGACAFQACAFAEADIAJAGQAFACAEAAQAFAAAFgCQAFgCAEgEQADgDADgFQACgFAAgGQAAgFgCgFQgDgFgDgDQgEgEgFgCQgFgCgFAAQgEAAgFACg");
	this.shape_17.setTransform(-49.2,-0.3);

	this.shape_18 = new cjs.Shape();
	this.shape_18.graphics.f("#FFFFFF").s().p("AgaAnIgDgBIgBgCIAAhHQAAgBAAAAQAAAAAAgBQABAAAAAAQAAAAAAAAIADgBIA2AAIACABIAAADIABACIAAADIgBADIgCACIgoAAIgCABIgBACIAAALIABACIACABIAaAAIACABIABADIAAADIAAACQAAABAAAAQAAABgBAAQAAABgBAAQAAABgBAAIgZAAIgDABIgBADIAAAMIAAADIADABIAoAAQADABgBADIAAADIAAADIgBACIgBABg");
	this.shape_18.setTransform(-60.5,-0.3);

	this.shape_19 = new cjs.Shape();
	this.shape_19.graphics.f("#FFFFFF").s().p("AABAoIgBAAIgFgBQAAgBAAAAQAAAAgBAAQAAgBAAAAQAAgBAAgBIAAg5QAAAAAAgBQAAAAAAAAQgBgBAAAAQAAAAgBgBIgDAAIgGgBIgGAAIgDABQgBAAAAAAQgBAAAAAAQgBgBAAAAQAAAAAAgBIgBgDIAAgDIABgDIABgCIACAAIA1AAQABAAAAAAQABAAAAAAQABAAAAAAQAAABAAAAIABADIAAADIgBACIgBADIgCABIgQAAIgCAAQgBABAAAAQAAAAgBABQAAAAAAABQAAAAAAABIAAA4IAAADIgDACg");
	this.shape_19.setTransform(-68,-0.2);

	this.shape_20 = new cjs.Shape();
	this.shape_20.graphics.f("#FFFFFF").s().p("AgRAmQgJgEgGgFIAAgCIAAgBIAAgDIACgDIAEgBIACgBIAEABIAFADIAHAEQADABAFAAIAFAAIAHgCIAEgEQADgCAAgEQAAgDgDgBQgCgCgDgBIgIgCIgJgCIgJgCQgFgBgDgBQgEgDgCgDQgCgEgBgGQABgHADgEQADgEAEgDQAFgDAGgCIALgBIAHAAIAIACIAHAEIAHAEIAAABIAAACIAAADIgDACIgDABIgDABIgCAAIgJgFQgFgCgFAAIgFAAIgFACQgCAAgCADQgCACAAADQAAAFAEABIAJADIAMACIAMACQAFACAEAEQAEAFgBAHQAAAHgDAGQgDAEgFAEQgFADgGABIgLACQgJAAgIgDg");
	this.shape_20.setTransform(-75,-0.2);

	this.shape_21 = new cjs.Shape();
	this.shape_21.graphics.f("#FFFFFF").s().p("AAdAnIgEAAQgBAAAAAAQgBgBAAAAQgBAAAAgBQAAAAAAgBIgFgKIgBgCIgCgBIgaAAIgBABIgBABIgCAAIAAABIgFAKIgBACIgCABIgDAAIgCAAIgCAAIgCAAIgCgBIgBgBIAghKQAAAAABAAQAAgBAAAAQAAAAABAAQAAAAAAAAIACgBIADAAIADACIAfBJIAAABIgBACIgCAAIgDABgAgBgLIgBACIgBAEIgCAFIgCADIgCAEIAAABIAAACIACABIAPAAIACgBIAAgCIgBgDIgDgFIgCgHIgCgEIgCgBIAAAAg");
	this.shape_21.setTransform(-82.6,-0.2);

	this.shape_22 = new cjs.Shape();
	this.shape_22.graphics.f("#FFFFFF").s().p("AABAoIgBAAIgFgBQAAgBAAAAQAAAAgBAAQAAgBAAAAQAAgBAAgBIAAg5QAAAAAAgBQAAAAAAAAQgBgBAAAAQAAAAAAgBIgEAAIgGgBIgGAAIgDABQgBAAAAAAQgBAAAAAAQgBgBAAAAQAAAAgBgBIAAgDIAAgDIAAgDIACgCIACAAIA2AAQAAAAAAAAQABAAAAAAQABAAAAAAQAAABAAAAIABADIAAADIgBACIgBADIgCABIgQAAIgCAAQgBABAAAAQAAAAgBABQAAAAAAABQAAAAAAABIAAA4IAAADIgDACg");
	this.shape_22.setTransform(-89.7,-0.2);

	this.shape_23 = new cjs.Shape();
	this.shape_23.graphics.f("#FFFFFF").s().p("AAdAnIgEAAQgBAAAAAAQgBgBAAAAQgBAAAAgBQAAAAAAgBIgFgKIgBgCIgCgBIgaAAIgBABIgBABIgCAAIAAABIgFAKIgBACIgCABIgDAAIgCAAIgCAAIgCAAIgCgBIgBgBIAghKQAAAAABAAQAAgBAAAAQAAAAABAAQAAAAAAAAIACgBIADAAIADACIAfBJIAAABIgBACIgCAAIgDABgAgBgLIgBACIgBAEIgCAFIgCADIgCAEIAAABIAAACIACABIAPAAIACgBIAAgCIgBgDIgDgFIgCgHIgCgEIgCgBIAAAAg");
	this.shape_23.setTransform(-100.1,-0.2);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_23},{t:this.shape_22},{t:this.shape_21},{t:this.shape_20},{t:this.shape_19},{t:this.shape_18},{t:this.shape_17},{t:this.shape_16},{t:this.shape_15},{t:this.shape_14},{t:this.shape_13},{t:this.shape_12},{t:this.shape_11},{t:this.shape_10},{t:this.shape_9},{t:this.shape_8},{t:this.shape_7},{t:this.shape_6},{t:this.shape_5},{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).wait(1));

}).prototype = getMCSymbolPrototype(lib.atasteofwholefoods, new cjs.Rectangle(-106,-7.7,212,15.5), null);


(lib.ctarollover = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// timeline functions:
	this.frame_0 = function() {
		this.stop();
	}
	this.frame_11 = function() {
		this.stop();
	}
	this.frame_23 = function() {
		this.stop();
	}

	// actions tween:
	this.timeline.addTween(cjs.Tween.get(this).call(this.frame_0).wait(11).call(this.frame_11).wait(12).call(this.frame_23).wait(7));

	// Layer 1
	this.instance = new lib.ctarollovervideo();
	this.instance.parent = this;
	this.instance.alpha = 0;

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1).to({alpha:1},9).wait(2).to({alpha:0},10).wait(8));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-56.7,-13,113.5,24);


// stage content:
(lib.RECOVER_largemobileatasteofseven = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// timeline functions:
	this.frame_57 = function() {
		//onhover event to reveal green cta rectangle over orange rectangle
		this.btn_main.addEventListener("mouseover", fl_MouseOverHandler.bind(this));
		this.btn_main.addEventListener("mouseout", fl_MouseOutHandler.bind(this));
		
		function fl_MouseOverHandler()
		{
			this.cta_rollover.gotoAndPlay(2);
		}
		
		function fl_MouseOutHandler()
		{
		this.cta_rollover.gotoAndPlay(13);
		}
	}
	this.frame_214 = function() {
		this.stop();
	}

	// actions tween:
	this.timeline.addTween(cjs.Tween.get(this).wait(57).call(this.frame_57).wait(157).call(this.frame_214).wait(5));

	// button
	this.btn_main = new lib.mainbutton();
	this.btn_main.parent = this;
	this.btn_main.setTransform(160.7,50.2,1.558,0.155,0,0,0,0.2,1.3);
	new cjs.ButtonHelper(this.btn_main, 0, 1, 2, false, new lib.mainbutton(), 3);

	this.timeline.addTween(cjs.Tween.get(this.btn_main).wait(219));

	// grey-rectangle
	this.instance = new lib.greyrectangle();
	this.instance.parent = this;
	this.instance.setTransform(160,50);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(219));

	// logo1
	this.instance_1 = new lib.whitelogouse();
	this.instance_1.parent = this;
	this.instance_1.setTransform(49.8,28.6);
	this.instance_1.alpha = 0;

	this.timeline.addTween(cjs.Tween.get(this.instance_1).wait(9).to({scaleX:0.08,scaleY:0.08,x:45,y:29.6},0).to({scaleX:1.59,scaleY:1.59,alpha:1},6).to({scaleX:1.51,scaleY:1.51},7).wait(197));

	// fade-from-white
	this.instance_2 = new lib.blackwideskyscraper();
	this.instance_2.parent = this;
	this.instance_2.setTransform(161.2,50.5,1.954,0.168,0,0,0,0.4,0.3);
	this.instance_2.filters = [new cjs.ColorFilter(0, 0, 0, 1, 255, 255, 255, 0)];
	this.instance_2.cache(-84,-302,168,604);

	this.timeline.addTween(cjs.Tween.get(this.instance_2).to({regX:0.2,scaleX:1.95,scaleY:0.17,x:160.3,y:50,alpha:0},9).wait(210));

	// mask (mask)
	var mask = new cjs.Shape();
	mask._off = true;
	mask.graphics.p("ArsCFIAAkIMAk+AAAIAAEIg");
	mask.setTransform(161.8,13.3);

	// a taste of whole foods market
	this.instance_3 = new lib.atasteofwholefoods();
	this.instance_3.parent = this;
	this.instance_3.setTransform(192.9,14.8);
	this.instance_3.alpha = 0;

	var maskedShapeInstanceList = [this.instance_3];

	for(var shapedInstanceItr = 0; shapedInstanceItr < maskedShapeInstanceList.length; shapedInstanceItr++) {
		maskedShapeInstanceList[shapedInstanceItr].mask = mask;
	}

	this.timeline.addTween(cjs.Tween.get(this.instance_3).wait(29).to({x:-32.2},0).to({x:202.9,alpha:1},10,cjs.Ease.get(1)).to({x:192.9},8,cjs.Ease.get(1)).wait(172));

	// mask (mask)
	var mask_1 = new cjs.Shape();
	mask_1._off = true;
	mask_1.graphics.p("ArsD1IAAkIMAk+AAAIAAEIg");
	mask_1.setTransform(161.8,24.5);

	// try-new-flavors
	this.instance_4 = new lib.trynewflavors();
	this.instance_4.parent = this;
	this.instance_4.setTransform(157.8,32.9);
	this.instance_4.alpha = 0;

	var maskedShapeInstanceList = [this.instance_4];

	for(var shapedInstanceItr = 0; shapedInstanceItr < maskedShapeInstanceList.length; shapedInstanceItr++) {
		maskedShapeInstanceList[shapedInstanceItr].mask = mask_1;
	}

	this.timeline.addTween(cjs.Tween.get(this.instance_4).wait(52).to({x:-32.2},0).to({x:162.8,alpha:1},10,cjs.Ease.get(1)).to({x:157.8},8,cjs.Ease.get(1)).wait(149));

	// mask (mask)
	var mask_2 = new cjs.Shape();
	mask_2._off = true;
	mask_2.graphics.p("ArsFjIAAkJMAk+AAAIAAEJg");
	mask_2.setTransform(161.8,35.5);

	// for-your-feast
	this.instance_5 = new lib.foryourfeast();
	this.instance_5.parent = this;
	this.instance_5.setTransform(150.1,56.6);
	this.instance_5.alpha = 0;

	var maskedShapeInstanceList = [this.instance_5];

	for(var shapedInstanceItr = 0; shapedInstanceItr < maskedShapeInstanceList.length; shapedInstanceItr++) {
		maskedShapeInstanceList[shapedInstanceItr].mask = mask_2;
	}

	this.timeline.addTween(cjs.Tween.get(this.instance_5).wait(62).to({x:-32.2},0).to({x:155.1,alpha:1},10,cjs.Ease.get(1)).to({x:150.1},8,cjs.Ease.get(1)).wait(139));

	// date
	this.instance_6 = new lib.noveleventwelve();
	this.instance_6.parent = this;
	this.instance_6.setTransform(261.8,56.6);
	this.instance_6.alpha = 0;

	this.timeline.addTween(cjs.Tween.get(this.instance_6).wait(84).to({alpha:1},10).wait(125));

	// mask (mask)
	var mask_3 = new cjs.Shape();
	mask_3._off = true;
	mask_3.graphics.p("ArMHgIAAkJMAk9AAAIAAEJg");
	mask_3.setTransform(164.9,48);

	// find-an-event
	this.instance_7 = new lib.findanevent();
	this.instance_7.parent = this;
	this.instance_7.setTransform(131.7,82.3);
	this.instance_7.alpha = 0;

	var maskedShapeInstanceList = [this.instance_7];

	for(var shapedInstanceItr = 0; shapedInstanceItr < maskedShapeInstanceList.length; shapedInstanceItr++) {
		maskedShapeInstanceList[shapedInstanceItr].mask = mask_3;
	}

	this.timeline.addTween(cjs.Tween.get(this.instance_7).wait(106).to({x:132.9,y:81.3},0).to({alpha:1},10).wait(103));

	// cta-rollover
	this.cta_rollover = new lib.ctarollover();
	this.cta_rollover.parent = this;
	this.cta_rollover.setTransform(143.7,83.1);

	this.timeline.addTween(cjs.Tween.get(this.cta_rollover).wait(219));

	// cta-rectangle
	this.instance_8 = new lib.ctarectangle();
	this.instance_8.parent = this;
	this.instance_8.setTransform(132.9,82);
	this.instance_8.alpha = 0;

	this.timeline.addTween(cjs.Tween.get(this.instance_8).wait(106).to({alpha:1},10).wait(103));

	// kale
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#006F46").s().p("A8ZJTIAAylMA4yAAAIAASlg");
	this.shape.setTransform(164.3,54.1);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#FFFFFF").s().p("AggA9QgJgDAAgGQAAgBAAAAQAAgBAAAAQAAgBAAAAQABAAAAAAQAAgBABAAQAAAAAAgBQABAAAAAAQABAAAAAAIAJADQAJACAIABQALgBAGgHQAHgHAAgMQAAgJgFgEQgGgGgMgFIgRgDQgJgBgBgEQAAgDAEgLIAHgbIAFgMIACgEIACgBIAGAAIA1AAQgCAMgCAEQgDADgJAAIgdAAIgIABIgDABIgEAKIgCAMQAAACAJACIALACQAVAGAJAJQAIAHAAAQQAAASgNAMQgOAMgUAAQgPAAgIgEg");
	this.shape_1.setTransform(293.3,65.4);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#FFFFFF").s().p("AgVAIIgBgDIAAgEIACgFIADgDQABgBAEAAIAEAAIAIAAIAPAAIADgBIAEABQAAABABAAQAAAAAAABQAAAAAAABQABAAAAABQAAAEgDAFQgEAEgDAAIgFAAIgFAAIgUAAIgCABQAAAAgBAAQAAAAgBgBQAAAAgBAAQAAAAAAgBg");
	this.shape_2.setTransform(285.1,65.6);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#FFFFFF").s().p("AAVBFIgHAAQgBgBAAgEIAAgcIgyAAQgIAAgCgBQgBgBAAgDQAAgIAbgjIAHgKIAHgJQAaglAIAAQAEAAABACQACACAAAHIAABPIAJAAIAFABQAAAAAAAAQABAAAAAAQAAABAAAAQAAABAAAAIAAAHIgBAEIgFAAIgJAAIAAAcQAAAEgBABIgGAAgAgJgJQgLAOgKARIArAAIAAg9IgWAeg");
	this.shape_3.setTransform(276.8,65.6);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#FFFFFF").s().p("AgJAKQgEgEAAgGQAAgFAEgEQAEgEAFAAQAGAAAEAEQAEAEAAAFQAAAGgEAEQgEAEgGAAQgFAAgEgEg");
	this.shape_4.setTransform(264.2,69.1);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#FFFFFF").s().p("AgJAmQgGgJgMgdIgGgOQgGgRgEgCIgDgBQgFgCAAgEQAAgDAFgCQAEgBAPAAQAMAAAFABQAEACAAADIgBADIgBACIgDABQgBABgBAAQAAAAgBABQAAAAAAABQgBAAAAABIADAHIAGASIAHARQACAEACAAIADgDIADgIIAKgWIAEgMIgBgDIgDgCIgCgBQgEgCAAgDQAAgDAEgCQAEgBAMAAQAJAAAEABQAEACAAADQAAAEgFABIgDABQgEACgIASIgDAGIgDAIQgVAvgFAAQgEAAgFgJg");
	this.shape_5.setTransform(257,65.9);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f("#FFFFFF").s().p("AghAiQgNgNABgVQAAgTANgOQAOgOATAAQAUAAANANQAMANAAAUQAAAUgNAPQgOAOgTAAQgTAAgOgOgAgRgaQgFAHAAAMQAAASAHAMQAIAMAKAAQAJAAAGgIQAGgHAAgNQgBgQgHgNQgIgMgKAAQgJAAgGAIg");
	this.shape_6.setTransform(247.1,65.7);

	this.shape_7 = new cjs.Shape();
	this.shape_7.graphics.f("#FFFFFF").s().p("AAJAZIgDgEIgUgYIgTgXIgHgJIgBAGIAAANIAAAIQAAAoABAJQACALADAAQACAAADACQACACABACQgBAFgEABQgFACgKgBQgLABgEgCQgFgBAAgFQABgDAEgCIAGgDQABgCABgNIABgjIgBgiQgBgOgBgCIgGgDQgEgDgBgDQABgDAEgBQADgCAMAAIAKAAIADACIAOAPIASAYIAUAZIAOARIAKAKIAAgDIAAgHIgBgtIgBgWIgCgCIgBgBIgHgDIgBgEQAAgEAEgBQADgBANAAIAPABQADABAAAEIgBAEIgDACIgCABQgEABgBACIgBAWIAAA3IAAARIAAALQAAAHgBABQAAABgBAAQAAAAAAABQgBAAAAAAQgBAAAAAAQgKAAgggpg");
	this.shape_7.setTransform(234.9,63.8);

	this.shape_8 = new cjs.Shape();
	this.shape_8.graphics.f("#FFFFFF").s().p("AgJAcQgBAAAAAAQAAgBAAAAQgBAAAAgBQAAAAAAAAIACgEIACgCIAFgKIACgHIgBgCIgDgBQgEgCgDgDQgCgEAAgFQAAgGAEgEQAEgEAFAAQAGAAAEAGQAEAFAAAIQAAAGgDAGQgCAHgGAJIgEAIIgEACIgEgBg");
	this.shape_8.setTransform(220.3,70.5);

	this.shape_9 = new cjs.Shape();
	this.shape_9.graphics.f("#FFFFFF").s().p("AgEA3QgFgBgDgDQgDgEgBgEQgCgGAAgNIAAgxIgIAAIgDAAIgBgCIAAgCQAAgEAKgIIAEgDIADgDQAJgIAEAAIACABIABABIAAASIAUAAIAEAAIABAEIAAACIgBADIgEABIgSAAIgCABIAAADIAAAsQAAAMACADQACADAFAAIAIgCIAGgBIADABQAAAAABABQAAAAAAAAQAAABAAAAQAAAAAAABQAAAFgHAFQgIAFgKgBQgFAAgEgBg");
	this.shape_9.setTransform(214.4,64.9);

	this.shape_10 = new cjs.Shape();
	this.shape_10.graphics.f("#FFFFFF").s().p("AgGAwIgJgCIgEACIgDAAIgBAAIgCgBQgDgDgDgHQgCgIAAgHQgBgCACgDQAAAAABAAQABgBAAAAQABAAAAAAQABgBAAAAQAEAAAEAIIAEAGQADADAFACQAFACAEAAQAGAAAEgDQADgDAAgFQAAgHgPgIIgEgDQgPgHgFgEQgFgHAAgJQAAgMAIgHQAIgIAOAAIAFABIAHABIAEgCIADAAQAFAAAEAHQAEAIAAAHQAAADgCACQAAABAAAAQgBAAAAABQgBAAAAAAQgBAAAAAAIgFgCIgEgGQgEgFgDgCQgEgDgFAAQgEAAgEADQgDADAAAFQAAAEADADQAEADAKAGIABAAQAZAMAAAPQAAANgKAJQgJAIgPAAg");
	this.shape_10.setTransform(207.1,65.7);

	this.shape_11 = new cjs.Shape();
	this.shape_11.graphics.f("#FFFFFF").s().p("AAQArIgFgFIgEACQgKAIgMAAQgNAAgIgIQgIgIAAgMQAAgPAKgHQALgIATAAQAEAAACABQABAAAAABQABAAAAABQAAAAAAABQAAABAAABQAAAEgFAAQgJAAgGAFQgFAEAAAIQAAAHAFAFQAEAEAIAAQAIAAAEgEQAEgEAAgJIAAgiQAAgIgDgFQgEgEgFAAQgFAAgEACQgEACgDAEIgCACQgGAHgGAAQgEAAgCgCQgCgCAAgEQAAgJALgGQAKgGARAAQAJAAAIADQAHADAEAFQADADABAGIABATIAAAcIABAIIACADIADABQAGABAAADQAAAFgGADQgGAEgIAAQgEAAgFgFg");
	this.shape_11.setTransform(198.5,65.7);

	this.shape_12 = new cjs.Shape();
	this.shape_12.graphics.f("#FFFFFF").s().p("AgdAjQgNgOAAgUQAAgUANgOQAOgOATAAQASAAAKAKQALAKAAASQAAAFgCACQgBACgIAAIgiAAQAAAAgBAAQgBAAAAgBQgBAAAAAAQgBAAAAgBQgBAAAAgBQAAAAgBgBQAAAAAAgBQAAAAAAgBQAAAAAAgBQAAAAAAgBQABAAAAgBQAAAAABAAQAAgBABAAQAAAAABAAQAAgBABAAQABAAAAAAIASAAIAGAAIAAgDQABgJgHgGQgGgGgHAAQgLAAgFAKQgGAJAAANQAAAOAIAKQAHALALAAQAGAAAFgCQAFgBAFgDIACgDQAFgEADAAQAAAAAAAAQABAAAAABQABAAAAAAQABAAAAABQAAAAABAAQAAABAAAAQAAAAAAABQAAAAAAABQAAACgCADIgGAGQgIAHgHADQgIADgIAAQgTAAgNgNg");
	this.shape_12.setTransform(188.7,65.7);

	this.shape_13 = new cjs.Shape();
	this.shape_13.graphics.f("#FFFFFF").s().p("AguBBQgFgBAAgFQAAgDAFgCIAGgDIACgQIABgjIgBghQgBgOgBgCIgGgDQgFgDAAgDQAAgEAFgBQAEgBAQAAIA3AAIAJgBIAFgBIACAAIABACIAEAKIACALQAAADgCACQgBADgDAAQgDAAgEgHIgDgEQgCgCgEgCQgEgCgGABIgNAAIgMABQgEAAgCACQgCACAAAGIgBASIAAAHQAAAEABACQAAAAAAAAQAAAAABABQAAAAABAAQABAAAAAAIAOAAQAIAAACgDQADgBABgGIAAgCQACgJAFgBQAEABABAFQACAEAAASQAAARgCAFQgBAEgEAAQgFABgCgKIAAgCQgBgGgDgCQgCgCgIAAIgOAAQAAAAgBABQAAAAgBAAQAAAAgBAAQAAABAAAAQgBACAAAFIAAAIIABAZQAAAGACABIAEACQAGACAAADQAAAFgGABQgFACgOAAQgPAAgFgCg");
	this.shape_13.setTransform(178.4,63.7);

	this.shape_14 = new cjs.Shape();
	this.shape_14.graphics.f("#FFFFFF").s().p("AgaAtQgFgBAAgEQAAgDAEgCIADgBQACgBABgEIABgKIAAgGIAAgHIAAgFQAAgQgBgFQAAgFgCgBIgFgCQgFgCAAgDQAAAAAAgBQAAAAAAgBQAAAAABgBQAAAAAAAAIAGgEIAMgEIAJgBQAEAAABAMIAAACIABAAQAFgHAFgEQAFgEAFAAQAGAAAEAEQAEADAAAHQgBAGgDAEQgCAEgGAAIgEgBIgEgDIgCgEIgCgBQgGAAgDAIQgCAJAAAbQAAAHABAEQABAEACACIAEABQAGACgBADQAAAEgEABQgGACgLAAQgOAAgEgCg");
	this.shape_14.setTransform(164.5,65.7);

	this.shape_15 = new cjs.Shape();
	this.shape_15.graphics.f("#FFFFFF").s().p("AAUAvIgBgFIAAgGIgBgBIgDACIgBACQgFAEgFACQgFADgHAAQgHAAgFgDQgHgDgEgEQgEgFgCgIQgCgHAAgTIABgGIAAgHIAAgCQAAgHgBgCQgBgCgEgCIgDgBQgGgBAAgDQAAgBAAAAQAAgBABAAQAAgBAAAAQABgBAAAAIAJgEIAMgDIAKgCQAAAAABAAQAAAAABABQAAAAABAAQAAABAAAAIABAGIAAAEIgBAiQAAASAEAHQAEAHAJAAQAKAAAEgJQAFgKAAgVIAAgHQAAgHgBgCQgBgCgDgCIgEgBQgFgBAAgDQAAgBAAAAQAAgBAAAAQAAgBABAAQAAgBABAAIAIgEIAMgDIAKgCQABAAAAAAQABAAAAABQABAAAAAAQABABAAAAIABAGIAAAFIgBAlIAAAPIAAAHQABADAFACIABABQAGABAAADQAAABAAAAQgBABAAABQAAAAAAAAQgBABAAAAIgGADIgNAEIgJACIgEgBg");
	this.shape_15.setTransform(155.2,65.7);

	this.shape_16 = new cjs.Shape();
	this.shape_16.graphics.f("#FFFFFF").s().p("AghAiQgMgNAAgVQAAgTANgOQAOgOATAAQAUAAANANQAMANAAAUQAAAUgNAPQgOAOgTAAQgUAAgNgOgAgQgaQgGAHAAAMQAAASAHAMQAIAMAKAAQAJAAAGgIQAGgHgBgNQAAgQgHgNQgIgMgKAAQgJAAgFAIg");
	this.shape_16.setTransform(144.8,65.7);

	this.shape_17 = new cjs.Shape();
	this.shape_17.graphics.f("#FFFFFF").s().p("AgTBAQgEgBAAgFQAAgDAFgCIAEgCQADgDAAglIAAgIIgLgRIgRgcQgFgHgDgCIgEgCQgHgCAAgEQAAgEAFgBQAEgBASAAQASAAAEABQAEABAAAEQAAAEgHADIgBAAIgCABIgBADIADAJIASAcIAQgXQAFgJAAgCQAAgBAAgBQAAAAAAgBQgBAAAAgBQAAAAgBgBQAAgBgFgBIgFgDIgBgEQABgEADgBQAEgBAPAAQAPAAAEABQADABAAAEQAAAEgEACIgHADQgFADgJAOIgVAjIAAAQQAAAfACACIAFACQAFACAAADQAAAFgEABQgGACgOAAQgNAAgGgCg");
	this.shape_17.setTransform(133.8,63.8);

	this.shape_18 = new cjs.Shape();
	this.shape_18.graphics.f("#FFFFFF").s().p("AgbAtQgEgBAAgEQAAgDAEgCIACgBQADgBABgEIABgKIAAgGIAAgHIAAgFQAAgQgBgFQgBgFgBgBIgFgCQgGgCAAgDQAAAAABgBQAAAAAAgBQAAAAABgBQAAAAABAAIAFgEIANgEIAIgBQAEAAABAMIAAACIAAAAQAGgHAEgEQAFgEAGAAQAGAAAEAEQADADAAAHQAAAGgCAEQgDAEgFAAIgFgBIgEgDIgCgEIgCgBQgGAAgCAIQgDAJAAAbQAAAHABAEQABAEADACIADABQAFACABADQAAAEgGABQgEACgNAAQgNAAgFgCg");
	this.shape_18.setTransform(119.5,65.7);

	this.shape_19 = new cjs.Shape();
	this.shape_19.graphics.f("#FFFFFF").s().p("AggAiQgOgNAAgVQAAgTAOgOQAOgOAUAAQATAAANANQANANAAAUQAAAUgOAPQgNAOgUAAQgTAAgNgOgAgQgaQgGAHAAAMQAAASAIAMQAHAMALAAQAIAAAGgIQAFgHAAgNQABgQgJgNQgHgMgKAAQgJAAgFAIg");
	this.shape_19.setTransform(110.7,65.7);

	this.shape_20 = new cjs.Shape();
	this.shape_20.graphics.f("#FFFFFF").s().p("AgZBCQgEgCAAgDQAAgDAEgCIACgBQADgBAAgDIABgLIAAgIIAAgsIgKAAQAAAAgBAAQAAAAgBAAQAAAAAAgBQgBAAAAAAIgBgEIAAgCIABgDIADgBIAKAAIgBgHIAAgHQAAgNAIgIQAIgIAPAAQAKAAAGAFQAHAEAAAIQAAAEgCACQgDACgEABQgDAAgCgCQgDgBgBgCIgCgEQgDgGgGAAQgDgBgCADQgBACAAAEIABAKQACAIAAAGIANAAIADABIABADIAAACIgBAEIgDABIgNAAIAAAuIABAQQABADABABIAEABQAFACAAAEQAAAEgEABIgRABIgSgBg");
	this.shape_20.setTransform(103.7,63.6);

	this.instance_9 = new lib.tablelargemobile();
	this.instance_9.parent = this;
	this.instance_9.setTransform(160.1,50.5,1,1.011,0,0,0,0.1,0.1);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.instance_9},{t:this.shape_20},{t:this.shape_19},{t:this.shape_18},{t:this.shape_17},{t:this.shape_16},{t:this.shape_15},{t:this.shape_14},{t:this.shape_13},{t:this.shape_12},{t:this.shape_11},{t:this.shape_10},{t:this.shape_9},{t:this.shape_8},{t:this.shape_7},{t:this.shape_6},{t:this.shape_5},{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).wait(219));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(142.6,44.6,363.5,119);
// library properties:
lib.properties = {
	id: '85088BD5353243C8B4895C262600CED3',
	width: 320,
	height: 100,
	fps: 24,
	color: "#FFFFFF",
	opacity: 1.00,
	webfonts: {},
	manifest: [
		{src:"images/largemobiletable.jpg", id:"largemobiletable"}
	],
	preloads: []
};



// bootstrap callback support:

(lib.Stage = function(canvas) {
	createjs.Stage.call(this, canvas);
}).prototype = p = new createjs.Stage();

p.setAutoPlay = function(autoPlay) {
	this.tickEnabled = autoPlay;
}
p.play = function() { this.tickEnabled = true; this.getChildAt(0).gotoAndPlay(this.getTimelinePosition()) }
p.stop = function(ms) { if(ms) this.seek(ms); this.tickEnabled = false; }
p.seek = function(ms) { this.tickEnabled = true; this.getChildAt(0).gotoAndStop(lib.properties.fps * ms / 1000); }
p.getDuration = function() { return this.getChildAt(0).totalFrames / lib.properties.fps * 1000; }

p.getTimelinePosition = function() { return this.getChildAt(0).currentFrame / lib.properties.fps * 1000; }

an.bootcompsLoaded = an.bootcompsLoaded || [];
if(!an.bootstrapListeners) {
	an.bootstrapListeners=[];
}

an.bootstrapCallback=function(fnCallback) {
	an.bootstrapListeners.push(fnCallback);
	if(an.bootcompsLoaded.length > 0) {
		for(var i=0; i<an.bootcompsLoaded.length; ++i) {
			fnCallback(an.bootcompsLoaded[i]);
		}
	}
};

an.compositions = an.compositions || {};
an.compositions['85088BD5353243C8B4895C262600CED3'] = {
	getStage: function() { return exportRoot.getStage(); },
	getLibrary: function() { return lib; },
	getSpriteSheet: function() { return ss; },
	getImages: function() { return img; }
};

an.compositionLoaded = function(id) {
	an.bootcompsLoaded.push(id);
	for(var j=0; j<an.bootstrapListeners.length; j++) {
		an.bootstrapListeners[j](id);
	}
}

an.getComposition = function(id) {
	return an.compositions[id];
}



})(createjs = createjs||{}, AdobeAn = AdobeAn||{});
var createjs, AdobeAn;